travis:
  secure:
    BINSTAR_TOKEN: hxDLU72kbEhl67AxjrZ8DinH+0y+sqWmY5XvH56UjoRfoXsRDnX01XwxwuoKg9Clg+9GXOpwP3ywQqPEFG47iBziTu5Mm62OsMgu1+NOwZn7jdEYpc+o8miJEuhmFaOLyztJm1l2u92ld8RP1DdlFjIYzVN/RMindGLFNYDtCfNWImli5p0pua70eofvZzwDBKxEnGgzCEtIaDkG2J+46Z0vIGmQQVXcEy0A+6vYNyz/rQLmIfpj1+OCICs5DLlSVEEyK6qqJ1//9UT1mCPjm/zUJunulacNzhRH4ybGRF+DJ6yhqFRSSyD17MkTcw8hIShRiFMGWr2XFPwxMVcoTarQAONwZ4wPaDPoIOPLp/E9H5wVkf9rFmCo3cnWE07vHeZEvyUsLIIyCOsHnO+PzkRMs4cZEIM24BlHJzcb3elt73rkhY5gcRu4CtWCn2q/7hFttxivMCPYkGNL+RTvbL6KOwwpZ+XuaxnKbQQY7UYCICTGgkd8UDW1G/zTf9fHPcyNyB6gUmVPWVbPRt1Ru2E7nFKYYQo8TmmsDscteHYmodCBJJgVokO7I7NLqAfhD0DDL/nAJKaDjaIT6NglPPN1AU/vUgh4srwuK4/emdrEt5xDK2/35WKbSca3SoWppmlHTONrz0yfxnpHJeKDLgqudeyktTUgLowAMq5GdjM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
