appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Epo2bkiANxvv7GLfAFYh3usni9u4Wk5pHLiwgSKjMFMxiylg2NI/WqOtVrM7Y+ZZD+Fe4buX/aKwFyPnoPDVzb+IlJ69K4oicVuHVUoRugfDHgDXoiuuldFvOSyiWXP+D4l1CbGykkAj8Ftmz9xlqeRrQ/Rhj9FRBRv4ICemXjuw7UWmdQ/y4vkDLoRYAea73ZUD0Mpy+VoMszpPsVe3obM7jQDNHOrsOEBFPFSWy0ebh072/xJhkMIiEqMlWKinCYyYfGD3BXqP8npOaL12EDmHOfY6cpEsnExvPpJ6MqDhR69kVaW8Dgas8SMxmPoCUXoJGwn0qblUop7DgAcqqUWjoCwgye0OEF2NG7wJG5fCmkywUyCo1QyvJtdtdG64mpknaxcTorQ7nHFzOsvTFvStKnbZ2dzJ0Xd4sgshCphAynn16UVVbRlQZHpvta+l9Y5Dbd1UnfOPa8aYLqqotkdca3RAkQHUA53uPr/DTcSheRqnAlkhr+GZYvQ1WHo/ITc3SJg8Z8bRFa/FgSzIM9o2e4bH8BagGRRcVO9gbWMXbStlGTj5bpHBTnv0uMef5X9GM5+23g+MuxUUeRVNNRf75KCdAdE45TwIlD6thysIhPor9rVKtlrJ3NAqrDwuHPSX/mrgZrK+aHpccQiazzLAOnv/emEpeDO118M6pW4=}
